[package]
name = "square"
version = "0.1.0"
authors = ["Jeffrey Brown <jeffrey@sabrient.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

